name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  NODE_ENV: production
  VITE_BASE_URL: '/ai-tutor/'
  VITE_APP_TITLE: 'AI Tutor Platform'

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Install dependencies
        run: |
          npm ci
          npm audit fix || true

      - name: Type check
        run: npm run type-check || true

      - name: Build project
        run: npm run build
        env:
          VITE_BASE_URL: '/ai-tutor/'
          VITE_APP_TITLE: 'AI Tutor Platform'
          NODE_ENV: production

      - name: Run tests
        run: npm run test || true

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
        if: github.ref == 'refs/heads/main'
